---
title: "Lab 01 - Hello R"
author: "Colin"
date: "1-10-2023"
output: github_document
---

## Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```

## Exercises

### Exercise 1

1846 rows and 3 variables/columns
variables are dataset, x, and y


datasaurus_dozen %>%
  count(dataset) %>%
  print(13)
#12 datasets


### Exercise 2


```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")

ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```


```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3


```{r plot-star, fig.height=3, fig.width=6}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")

ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r cor-star}
star_data %>%
  summarize(r = cor(x, y))
```
Answer: star correlation (-.0630) and dino correlation (-.0645) are almost the same

### Exercise 4

```{r plot-circle, fig.height=3, fig.width=6}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")

ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r cor-circle}
circle_data %>%
  summarize(r = cor(x, y))
```

### Exercise 5

```{r}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
  geom_point()+
  facet_wrap(~ dataset, ncol = 3) +
  theme(legend.position = "none")
```

```{r}
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y)) %>%
  print(13)
```

